language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - npm run build:prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "Ln3S4DZIljt+zeEb3RBosSWTi8Jw/mDriGH+61RJrhMRu0lWBvGdMzAwY4HnEwsu+vu3Tg8qLR03r1rQNMeAWK0ogMIm4W/NnOYhngHVQHp4D4lp8Ar7kbaElEgA5lkDVEjpdg3lXiE8IqZsOSWsVyubH7kSVhKnwVFpv2msSVVNWGo3xhcxzm3a6toDWWNfYCpUGvh0muiXTq61mxIXWVIUwOFerwAVjWfulPdAojG85O0OGhqB3Bhk5ZVimYEyZC5wau/VYi6s/0buhYvL8wPrw82uNM9XvwiIUL4GfyebFbv5rXyZu0DtxP1Z3V8zIRbJq6CGbedD+815swrljIQODgDdD+TTjt955yPPUJFIvHzevUH2r0ao6WOXsqJP+NBgiJckr6eotR3yJHdg7XgIPXKkmKWZjJCL77/pacSH9jDKmO8jvYKhG4FAYSltO7KkBCYQNLFC6e7CG2IIlqoe5FiS6cq+lBDN9UCRWU9vGoh4Mcf3R6GHDWttXipbXorN+6yeMR1W4fE+/5Z8NIKTDZDay6m4yr9Zh+fXkuiG6je0IIIZVImLcvUj3megpViz8Ee6+85hSMG8m4IKQXbiC7O4ZrCrpVz4uGhT5MjmTK4HbW7RuGyC5MaAcEOQXtz7kSQ/o6SrmQPwzkEjOgVm/6fZz79bQwJnGh8ZD40="